name: iOS Build

on:
  push:
    branches:
      - development
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build
        run: ./gradlew :shared:iosX64Test

      - name: Build
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          workspace: templateios/templateios.xcworkspace
          scheme: templateios
          destination: name=iPhone 8
          sdk: iphoneos
          configuration: Debug
          action: build